/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Models.DAO.Banco;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;



/**
 *
 * @author Giullia
 */
public class Cliente extends javax.swing.JFrame {
    



    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        
        
        
        
    }
    
    
    public Cliente(String id, String nome, String sexo, String dataNascimento, String telefone, String rg, String endereco, String cep) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jTextID1 = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextRG = new javax.swing.JTextField();
        jLabelRG = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jTextEndereco = new javax.swing.JTextField();
        jLabelCEP = new javax.swing.JLabel();
        jTextCEP = new javax.swing.JTextField();
        jTextTelefone = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextSxo = new javax.swing.JTextField();
        jLabelSexo = new javax.swing.JLabel();
        jTextNascimento = new javax.swing.JTextField();
        jLabelNascimento = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Cadastro Paciente");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));
        getContentPane().add(jTextID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 260, 50));

        jLabelID.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabelNome.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));
        getContentPane().add(jTextNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 400, 50));

        jTextRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRGActionPerformed(evt);
            }
        });
        getContentPane().add(jTextRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 260, 50));

        jLabelRG.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelRG.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRG.setText("RG");
        getContentPane().add(jLabelRG, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabelEndereco.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEndereco.setText("Endereço");
        getContentPane().add(jLabelEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));
        getContentPane().add(jTextEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 490, 50));

        jLabelCEP.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelCEP.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCEP.setText("CEP");
        getContentPane().add(jLabelCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));
        getContentPane().add(jTextCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 250, 50));
        getContentPane().add(jTextTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 250, 50));

        jLabelTelefone.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));
        getContentPane().add(jTextSxo, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 250, 50));

        jLabelSexo.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Sexo");
        getContentPane().add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));
        getContentPane().add(jTextNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 250, 50));

        jLabelNascimento.setFont(new java.awt.Font("Berlin Sans FB", 0, 28)); // NOI18N
        jLabelNascimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNascimento.setText("Data de Nascimento");
        getContentPane().add(jLabelNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jButtonCadastrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 730, 40));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/CadastroFundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRGActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        MenuPrincipal telaMenu = new MenuPrincipal();
        telaMenu.setVisible(true);
        Cliente mensagem = new Cliente();
        mensagem.exibeMensagem();
        Cliente cliente = (Cliente) SwingUtilities.getRoot(this);
        ((Window) cliente).dispose();
        
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNascimento;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextCEP;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextID1;
    private javax.swing.JTextField jTextNascimento;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextRG;
    private javax.swing.JTextField jTextSxo;
    private javax.swing.JTextField jTextTelefone;
    // End of variables declaration//GEN-END:variables

    
    
    private void iniciar() {
        
        
      
    }

    public JButton getjButtonCadastrar() {
        return jButtonCadastrar;
        
    }

    public void setjButtonCadastrar(JButton jButtonCadastrar) {
        this.jButtonCadastrar = jButtonCadastrar;
    }

    public Object getjTextFieldId() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JTextField getjTextCEP() {
        return jTextCEP;
    }

    public void setjTextCEP(JTextField jTextCEP) {
        this.jTextCEP = jTextCEP;
    }

    public JTextField getjTextEndereco() {
        return jTextEndereco;
    }

    public void setjTextEndereco(JTextField jTextEndereco) {
        this.jTextEndereco = jTextEndereco;
    }

    public JTextField getjTextID1() {
        return jTextID1;
    }

    public void setjTextID1(JTextField jTextID1) {
        this.jTextID1 = jTextID1;
    }

    public JTextField getjTextNascimento() {
        return jTextNascimento;
    }

    public void setjTextNascimento(JTextField jTextNascimento) {
        this.jTextNascimento = jTextNascimento;
    }

    public JTextField getjTextNome() {
        return jTextNome;
    }

    public void setjTextNome(JTextField jTextNome) {
        this.jTextNome = jTextNome;
    }

    public JTextField getjTextRG() {
        return jTextRG;
    }

    public void setjTextRG(JTextField jTextRG) {
        this.jTextRG = jTextRG;
    }

    public JTextField getjTextSxo() {
        return jTextSxo;
    }

    public void setjTextSxo(JTextField jTextSxo) {
        this.jTextSxo = jTextSxo;
    }

    public JTextField getjTextTelefone() {
        return jTextTelefone;
    }

    public void setjTextTelefone(JTextField jTextTelefone) {
        this.jTextTelefone = jTextTelefone;
    }

    private void exibeMensagem() {
        JOptionPane.showMessageDialog(null, "Paciente Cadastrado com Sucesso!");
    }
    
}

    
    
    

