/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Window;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.SwingUtilities;


/**
 *
 * @author Giullia
 */
public class Relatorio extends javax.swing.JFrame {
    

    
    

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 680, 150, 40));

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aline Barros", "F", "32", "01/04/2020", "88", "02/12/2020"},
                {"Eduardo Machado", "M", "25", "05/06/2020", "74", "19/12/2020"},
                {"Jóse Márcio", "M", "56", "08/11/2020", "96", null},
                {"Maria Antônia", "F", "15", "24/11/2020", "65", "15/12/2020"},
                {"Kati Nunes", "F", "43", "10/10/2020", "71", "14/12/2020"},
                {"Livia Saguie", "F", "18", "14/11/2020", "61", null},
                {"Karlos Eduardo", "M", "30", "01/03/2020", "80", "01/12/2020"},
                {"Matheus Da Silva", "M", "26", "03/03/2020", "86", "30/11/2020"},
                {"Luiz Rodrigues", "M", "68", "30/06/2020", "78", "14/12/2020"},
                {"Francine Gomes", "F", "40", "15/03/2020", "80", "12/12/2020"},
                {"Lucas Cardoso", "M", "25", "22/11/2020", "90", "02/02/2021"},
                {"Gabriela Matos", "F", "35", "14/11/2020", "150", null}
            },
            new String [] {
                "Paciente", "Sexo", "Idade", "Última Consulta", "KGs", "Próxima Consulta"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 930, 580));

        jLabelTitulo.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabelTitulo.setText("Relatório");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        MenuPrincipal teladeMenu = new MenuPrincipal();
        teladeMenu.setVisible(true);
        Relatorio relatorio = (Relatorio) SwingUtilities.getRoot(this);
        ((Window) relatorio).dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        
    }

    public JTable getjTabela() {
        return jTabela;
    }

    public void setjTabela(JTable jTabela) {
        this.jTabela = jTabela;
    }
    
    
}
